# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/practice',
                'doc_host': 'https://tesfaasmara.github.io',
                'git_url': 'https://github.com/tesfaasmara/practice',
                'lib_path': 'practice'},
  'syms': { 'practice.Account': {},
            'practice.Bank1_OneAccount': {},
            'practice.Bank2_OneAccountWithFunctions': {},
            'practice.HigherOrLower': {},
            'practice.core': {'practice.core.foo': ('core.html#foo', 'practice/core.py')},
            'practice.friday': {},
            'practice.ride': {'practice.ride.translate': ('usaco/chapter1/ride/ride.html#translate', 'practice/ride.py')}}}