# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/practice',
                'doc_host': 'https://TesfaAsmara.github.io',
                'git_url': 'https://github.com/TesfaAsmara/practice',
                'lib_path': 'practice'},
  'syms': {'practice.core': {'practice.core.foo': ('core.html#foo', 'practice/core.py')}}}